import re
from typing import List, Dict, Any, Tuple

def verify_citations(answer: str, context_chunks: List[Dict[str, Any]]) -> Tuple[str, List[str]]:
    """
    Post-generation safety guard:
    Scans generated answer text for section citations (e.g. 'Section 15', 'Section 66D', 'Section 103').
    Cross-references each cited section against the combined text of all retrieved context chunks.
    If a section number is NOT present in any retrieved context chunk, it is flagged as an uncited/hallucinated citation.
    
    Returns:
      cleaned_answer: Answer text with hallucinated section citations flagged or redacted.
      hallucinated_sections: List of section numbers that were cited by LLM but absent from context.
    """
    if not context_chunks or not answer:
        return answer, []

    retrieved_text = " ".join([c.get("text", "") for c in context_chunks]).lower()

    pattern = r'\b(?:Section|Sec|u/s|s\.)\s*(\d+[A-Za-z]?(?:\(\d+\))*(?:\([a-z]+\))*)\b'
    matches = list(re.finditer(pattern, answer, flags=re.IGNORECASE))

    hallucinated_sections = []
    
    for match in matches:
        full_citation = match.group(0)
        sec_num = match.group(1)
        base_sec_match = re.match(r'^\d+[A-Za-z]?', sec_num)
        base_sec = base_sec_match.group(0) if base_sec_match else sec_num
        
        sec_regex = r'\b' + re.escape(base_sec) + r'\b'
        if not re.search(sec_regex, retrieved_text, re.IGNORECASE):
            hallucinated_sections.append(full_citation)

    hallucinated_sections = list(set(hallucinated_sections))

    if hallucinated_sections:
        disclaimer = f"\n\n[Citation Verification Warning: The following section citation(s) were generated by LLM memory but not present in retrieved context chunks: {', '.join(hallucinated_sections)}]"
        answer = answer + disclaimer

    return answer, hallucinated_sections


# Unit test
test_chunks = [
    {"text": "Section 15 of the Payment of Wages Act, 1936 states that where any deduction has been made from the wages of an employed person..."}
]

test_answer_valid = "According to Section 15 of the Payment of Wages Act, 1936, an employee may apply..."
test_answer_hallucinated = "According to Section 317 of the Bharatiya Nyaya Sanhita, 2023 and Section 15 of the Payment of Wages Act..."

ans1, h1 = verify_citations(test_answer_valid, test_chunks)
print("Valid answer hallucinations:", h1)
print("Valid answer output:\n", ans1)

ans2, h2 = verify_citations(test_answer_hallucinated, test_chunks)
print("\nHallucinated answer hallucinations:", h2)
print("Hallucinated answer output:\n", ans2)
